### ISSUE TITLE
about testing other datasets

### ISSUE THREAD

**Issue by Catherinehui** [wngh1187/ExU-Net#6]
Hi, I trained the model according to your guidance, but is there a special testing section? What if I want to test the trained model on other datasets?Such as Voices ?

**Comment by wngh1187** [comment]
hello. Thank you for your interest in our research.

If you would like to evaluate the model on other datasets, you can follow the steps below.

1. download an external dataset and define a dataloader
2. load the trained model
3. extract speaker embeddings corresponding to each utterance.
4. derive the score for the trial and calculate the final EER

With the exception of step 1, you can utilize parts of the training code.

**Comment by Catherinehui** [comment]
Thank you very much for your answer, I will try, but at present I have an error when using a single card GPU training, I wonder if you have encountered it when using a single card? As follows:
 Traceback (most recent call last):
  File "/home/wangzh22/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/wangzh22/paper_exunet_pro/ExU-mun/main.py", line 140, in run
    trainer.run()
  File "/home/wangzh22/paper_exunet_pro/ExU-mun/trainers/train.py", line 31, in run
    self.test(epoch)
  File "/home/wangzh22/paper_exunet_pro/ExU-mun/trainers/train.py", line 125, in test
    self.embeddings = self._enrollment()
  File "/home/wangzh22/paper_exunet_pro/ExU-mun/trainers/train.py", line 197, in _enrollment
    embedding_dict[keys[i]] = embeddings[i]
TypeError: unhashable type: 'list'
