### ISSUE TITLE
about single GPU

### ISSUE THREAD

**Issue by Catherinehui** [wngh1187/ExU-Net#7]
Hello, I recently found a problem when reproducing the experimental results, the original was to use multi-GPU training, but these two days, the resources are limited, and found that the model can not run normally on a single gpu training, may I ask you have encountered this problem, do you have a single gpu training version, thank you very much, here is my error:
Traceback (most recent call last):
  File "/home/wangzh22/anaconda3/envs/my_pytorch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/wangzh22/pycharm/ExU-light/main.py", line 140, in run
    trainer.run()
  File "/home/wangzh22/pycharm/ExU-light/trainers/train.py", line 31, in run
    self.test(epoch)
  File "/home/wangzh22/pycharm/ExU-light/trainers/train.py", line 125, in test
    self.embeddings = self._enrollment()
  File "/home/wangzh22/pycharm/ExU-light/trainers/train.py", line 201, in _enrollment
    embedding_dict[keys[i]] = embeddings[i]
TypeError: unhashable type: 'list'

**Comment by wngh1187** [comment]
Hello. 
I'm guessing that the error you're experiencing is due to converting code written for multiple GPUs to a single GPU environment.
I will update the ExU-Net training code for a single GPU as soon as possible.
